name: Build Bun App
on:
  push:
    branches: [ main ]
    tags:
      - 'v*' # Trigger jalan kalau lo push tag seperti v1.0, v2.1, dll.

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
       
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Build Executable
        run: |
          bun build ./index.ts --compile --target bun-linux-x64 --outfile pythagoras-linux
          bun build ./index.ts --compile --target bun-windows-x64 --outfile pythagoras-win.exe
          
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: pythagoras-apps
          path: |
            pythagoras-linux
            pythagoras-win.exe
            
      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: |
            pythagoras-linux
            pythagoras-win.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}